stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: maven:3.8.1-jdk-17
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:3.8.1-jdk-17
  script:
    - mvn test

package:
  stage: package
  image: maven:3.8.1-jdk-17
  script:
    - mvn package

deploy:
  stage: deploy
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  script:
    - docker build -t your-docker-image-name .
    - docker login -u your-docker-username -p your-docker-password
    - docker push your-docker-image-name