image: maven:3.8.3-openjdk-17

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375


stages:
  - build
  - docker_build
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn --batch-mode package

docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker --version
    - ip addr
    # - cat /etc/docker/daemon.json
    # - export DOCKER_HOST=tcp://localhost:2376 && docker build -t taewook/spring-boot-test .
    - export DOCKER_HOST=tcp://172.17.0.8:2375 && docker build -t taewook/spring-boot-test .
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -t taewook/spring-boot-test .
    - docker push taewook/spring-boot-test

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s-deployment.yaml

