image: maven:3.8.3-openjdk-17

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:20.10.8-dind

stages:
  - build
  - docker_build
  - deploy

cache:
  paths:
    - .m2/repository

before_script:
  - apk add docker-cli

build:
  stage: build
  script:
    - mvn --batch-mode package

docker_build:
  stage: docker_build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker --version
    - docker ps
    - docker build -t taewook/spring-boot-test .
    - docker push taewook/spring-boot-test

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s-deployment.yaml
